# Generated by Django 4.2.5 on 2023-12-13 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_freelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Clients'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='edu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='exp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='FL_PP'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='qual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='workdesc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='worktype',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='req')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pastprojects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='PP')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
